#*******************************************************************************
# Licensed Materials - Property of IBM
# IBM Cloud Code Engine, 5900-AB0
# © Copyright IBM Corp. 2020
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#*******************************************************************************


---
apiVersion: build.dev/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: functions-buildpacks
spec:
  buildSteps:
    - name: step-prepare
      image: gcr.io/projectriff/builder:0.18.0
      securityContext:
        runAsUser: 0
        capabilities:
          add: ["CHOWN"]
      command:
        - /bin/bash
      args:
        - -c
        - >
          chown -R "1000:1000" "/workspace/source" &&
          chown -R "1000:1000" "/tekton/home"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
    - name: step-detect
      image: gcr.io/projectriff/builder:0.18.0
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/detector
      args:
        - -app=/workspace/source/$(build.source.contextDir)
        - -group=/layers/group.toml
        - -plan=/layers/plan.toml
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-restore
      image: gcr.io/projectriff/builder:0.18.0
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/restorer
      args:
        - -layers=/layers
        - -cache-dir=/cache
        - -group=/layers/group.toml
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 512Mi
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
    - name: step-build
      image: gcr.io/projectriff/builder:0.18.0
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/builder
      args:
        - -app=/workspace/source/$(build.source.contextDir)
        - -layers=/layers
        - -group=/layers/group.toml
        - -plan=/layers/plan.toml
      resources:
        limits:
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 512Mi
        requests:
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 512Mi
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-export
      image: gcr.io/projectriff/builder:0.18.0
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/exporter
      args:
        - -app=/workspace/source/$(build.source.contextDir)
        - -layers=/layers
        - -cache-dir=/cache
        - -group=/layers/group.toml
        - $(build.output.image)
      resources:
        limits:
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 512Mi
        requests:
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 512Mi
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
